version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hsm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hsm_admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hsm_dev
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: hsm-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
